name: Bump formulae

on:
  schedule:
    - cron: "0 6 * * *" # daily at 06:00 UTC
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Trust tap
        run: brew trust cytsai1008/tap

      - name: Bump brew-cnf
        uses: dawidd6/action-homebrew-bump-formula@v7
        with:
          token: ${{ secrets.GH_PAT }}
          tap: cytsai1008/tap
          formula: brew-cnf
